[Interface]
Address = 10.0.0.2/24
PrivateKey = {privatekey}
DNS = 1.1.1.1

[Peer]
# Servidor WireGuard (Docker)
PublicKey = {publickey}
PresharedKey = pHvyw/AwUpITOj0mVXnqytrp8HEVc1R6lTVhi/T5ea4=
Endpoint = 192.168.15.4:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
