[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = {privatekey}

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Meu PC (app WireGuard)
PublicKey = {publickey}
PresharedKey = pHvyw/AwUpITOj0mVXnqytrp8HEVc1R6lTVhi/T5ea4=
AllowedIPs = 10.0.0.2/32
