[Interface]
Address = 10.0.0.2/24
PrivateKey = YLiCgxbwgmT/HLRGH2CWLPN/k9qDF4fZTfSPGDrCRmU=
DNS = 1.1.1.1

[Peer]
# Servidor WireGuard (Docker)
PublicKey = huVjqLIEEq/sFjJos5Qr1B4pLUyK/9xdNQN8t/ZonBE=
PresharedKey = pHvyw/AwUpITOj0mVXnqytrp8HEVc1R6lTVhi/T5ea4=
Endpoint = 192.168.15.4:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
