[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = iLz+fDWrfO9UI2i/kuAw+7oWK+69ghIn3LxryM20dGQ=

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Meu PC (app WireGuard)
PublicKey = TuLClX217aDl3vuS9y5tKLbRT83qE0htTHhp0bz6Slw=
PresharedKey = pHvyw/AwUpITOj0mVXnqytrp8HEVc1R6lTVhi/T5ea4=
AllowedIPs = 10.0.0.2/32
